#开发环境配置
spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/fescar?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true&amp;useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  redis:
    host:
    password:
    port: 6379
    database: 0
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 10
    timeout: 10000
#开发环境打印sql
logging:
  level:
    com.company.project.biz.mapper: debug
